version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SENTRY_AUTH_FRONTEND: ${SENTRY_AUTH_FRONTEND}
        SENTRY_AUTH_BACKEND: ${SENTRY_AUTH_BACKEND}
    ports:
      - "8080:4000"
    environment:
      - URL=http://localhost:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
