version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:4000"
    environment:
      - URL=http://localhost:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
